// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, forwardRef, useImperativeHandle } from "react";
import {
  useGLTF,
  useAnimations,
  Html,
  useContextBridge,
} from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import * as THREE from "three";
import "@/components/sample/laptopSample.css";
import { useFrame, useThree } from "@react-three/fiber";
import Works from "@/components/react/sections/Work";
import Navbar from "@/components/react/navbar";
import { DarkModeContext } from "@/components/react/context/DarkModeContext";
import { useTranslation } from "react-i18next";
import { Poppins } from "next/font/google";
import Image from "next/image";
import { useState } from "react";
import WallCertificates from "@/components/3D/components/WallCertificates";

export interface MyRoomHandle {
  screen: THREE.Object3D | null;
  cup: THREE.Object3D | null;
  wallDecor: THREE.Object3D[];
}

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

const MyRoom = forwardRef<
  MyRoomHandle,
  {
    setCamera: React.Dispatch<React.SetStateAction<boolean>>;
    isCameraAnimating: boolean;
    finishedCameraAnimating: boolean;
    sceneEffectsActive: boolean;
    showWallHtml: boolean;
  }
>(
  (
    {
      setCamera,
      isCameraAnimating,
      finishedCameraAnimating,
      sceneEffectsActive,
      showWallHtml,
      ...rest
    }: {
      setCamera: React.Dispatch<React.SetStateAction<boolean>>;
      isCameraAnimating: boolean;
      finishedCameraAnimating: boolean;
      sceneEffectsActive: boolean;
      showWallHtml: boolean;
    },
    ref
  ) => {
    const [hoveredImageCat, setHoveredImageCat] = useState(false);
    const [hoveredImageCouple, setHoveredImageCouple] = useState(false);
    const [hoveredImageCertificate1, setHoveredImageCertificate1] =
      useState(false);
    const [hoveredImageCertificate2, setHoveredImageCertificate2] =
      useState(false);
    const group = useRef<THREE.Group>(null);
    const screenRef = useRef<THREE.Mesh>(null);
    const animatedCupRef = useRef<THREE.Group>(null);
    const wallPictureBrownRef = useRef<THREE.Group>(null);
    const wallPictureBlackRef = useRef<THREE.Group>(null);
    const wallPictureRedRef = useRef<THREE.Group>(null);
    const scaleLevel = 1 / 0.085;
    const buttonToScreenRef = useRef<THREE.Group>(null);
    const { invalidate } = useThree();
    const { t } = useTranslation("");

    // const [screenSize, setScreenSize] = useState({ width: 0, height: 0 });
    // Context Bridge to connect with outside context
    const DarkModeContextBridge = useContextBridge(DarkModeContext);

    // Allow parent to access internal elements like Screen
    useImperativeHandle(ref, () => ({
      screen: screenRef.current,
      cup: animatedCupRef.current,
      wallDecor: [
        wallPictureBrownRef.current,
        wallPictureBlackRef.current,
        wallPictureRedRef.current,
      ].filter((g): g is THREE.Group => g != null),
    }));

    const { nodes, materials, animations } = useGLTF(
      "/models/isometric_room_fin_3.glb",
      true
    );

    // execute the animations
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
      const box = new THREE.Box3().setFromObject(group.current);
      const size = new THREE.Vector3();
      const center = new THREE.Vector3();
      box.getSize(size);
      box.getCenter(center);
    }, []);

    // get and set screen size
    // useEffect(() => {
    //   const mesh = nodes?.Plane031;
    //   if (mesh) {
    //     const box = new THREE.Box3().setFromObject(mesh);
    //     const size = new THREE.Vector3();
    //     box.getSize(size);
    //     setScreenSize({
    //       width: size.x,
    //       height: size.y,
    //     });
    //   }
    // }, [nodes]);

    // // add box helper
    // useEffect(() => {
    //   if (screenRef.current) {
    //     const mesh = nodes?.Plane031;
    //     const boxHelper = new THREE.BoxHelper(mesh, 0xff0000);
    //     group.current?.add(boxHelper);
    //   }
    // }, []);

    // Add mesh dimension measurement for picture frame
    // useEffect(() => {
    //   const mesh = nodes?.Cube037_0; // The current mesh for the picture frame
    //   if (mesh) {
    //     const box = new THREE.Box3().setFromObject(mesh);
    //     const size = new THREE.Vector3();
    //     box.getSize(size);
    //     console.log("Current picture frame dimensions:", {
    //       width: size.x,
    //       height: size.y,
    //       depth: size.z,
    //       scale: mesh.scale,
    //     });
    //   }
    // }, [nodes]);

    // Cup animation — only while scene effects are active (cup in view, etc.)
    useEffect(() => {
      const action = actions["Cylinder.006_0Action.004"];
      if (!action) return;

      action.setLoop(THREE.LoopOnce, 1);

      if (!sceneEffectsActive) {
        action.stop();
        return;
      }

      let timeoutId: ReturnType<typeof setTimeout> | undefined;

      const playWithDelay = () => {
        action.reset().fadeIn(0.5).play();
        const duration = action.getClip().duration;
        timeoutId = setTimeout(
          () => playWithDelay(),
          (duration + 1.1) * 1000
        );
      };

      playWithDelay();

      return () => {
        if (timeoutId !== undefined) clearTimeout(timeoutId);
        action.stop();
      };
    }, [actions, sceneEffectsActive]);

    useGSAP(() => {
      if (group.current) {
        gsap.from(group.current.rotation, {
          y: Math.PI / 2,
          duration: 1,
          ease: "power3.out",
          onUpdate: () => invalidate(),
        });
        group.current.traverse((child) => {
          if (child.isMesh) {
            child.castShadow = true;
            child.receiveShadow = true;
          }
        });
      }
    }, []);

    // Double sided
    useEffect(() => {
      materials["matte.001"].side = THREE.DoubleSide;
      materials["aluminium"].side = THREE.DoubleSide;
    }, [materials]);

    useFrame(({ camera }) => {
      if (buttonToScreenRef.current) {
        buttonToScreenRef.current.lookAt(camera.position);
      }
    });

    // Keep demand frameloop alive while scene effects animations are active,
    // but throttle redraws to reduce CPU usage.
    useEffect(() => {
      if (!sceneEffectsActive) return;

      let rafId = 0;
      let lastDraw = 0;
      const targetFrameMs = 1000 / 24; // 24 FPS is enough for subtle room effects

      // loops forever to 
      const tick = (now: number) => {
        if (now - lastDraw >= targetFrameMs) {
          invalidate();
          lastDraw = now;
        }
        rafId = window.requestAnimationFrame(tick);
      };
      rafId = window.requestAnimationFrame(tick);

      return () => {
        if (rafId) window.cancelAnimationFrame(rafId);
      };
    }, [sceneEffectsActive, invalidate]);

    const overlayScrollRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
      invalidate();
    }, [isCameraAnimating, finishedCameraAnimating, invalidate]);

    useEffect(() => {
      if (!showWallHtml) {
        setHoveredImageCat(false);
        setHoveredImageCouple(false);
        setHoveredImageCertificate1(false);
        setHoveredImageCertificate2(false);
      }
    }, [showWallHtml]);

    useEffect(() => {
      if (finishedCameraAnimating) {
        const timer = setTimeout(() => {
          overlayScrollRef.current?.scrollTo({
            top: 50,
            behavior: "smooth",
          });
        }, 1000);
        return () => clearTimeout(timer);
      }
    }, [finishedCameraAnimating]);

    return (
      // increase everything by 1/0.085 to fix the scale error of laptop screen
      <group scale={scaleLevel}>
        <group ref={group} {...rest} dispose={null}>
          <group name="Scene">
            <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Root">
                <group
                  ref={animatedCupRef}
                  name="AnimatedCup"
                  position={[0.011, 0.441, 0.532]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Cup"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup.geometry}
                    material={materials["material_8.002"]}
                    position={[0, 0.063, 0]}
                    rotation={[-1.564, 0.005, 0.643]}
                    scale={[0.063, 0.055, 0.085]}
                  />
                  <mesh
                    name="Steam"
                    castShadow
                    receiveShadow
                    geometry={nodes.Steam.geometry}
                    material={nodes.Steam.material}
                    position={[0.001, 0.075, -0.001]}
                    rotation={[0, 0, -Math.PI]}
                    scale={[0.022, 0.001, 0.021]}
                  />
                  <group
                    name="SteamWind"
                    position={[0.005, 0.139, 0.022]}
                    rotation={[-1.564, -0.004, -0.553]}
                    scale={[0.824, 0.531, 1.034]}
                  />
                </group>
                <group
                  name="BarByWindow1"
                  position={[-0.958, 0.73, 0.985]}
                  scale={[0.053, 0.053, 1.073]}
                >
                  <mesh
                    name="Cylinder010_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder010_0.geometry}
                    material={materials["tubes.005"]}
                  />
                </group>
                <group
                  name="BarByWindow2"
                  position={[-0.958, -0.857, 0.985]}
                  scale={[0.053, 0.053, 1.073]}
                >
                  <mesh
                    name="Cylinder013_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder013_0.geometry}
                    material={materials["tubes.005"]}
                  />
                </group>
                <group
                  name="BedBlanketBlack"
                  position={[0.246, -0.403, 1.37]}
                  rotation={[-1.218, 0.361, -0.994]}
                  scale={[0.942, 0.79, 0.573]}
                >
                  <mesh
                    name="Cube023_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube023_0.geometry}
                    material={materials["Material.017"]}
                  />
                </group>
                <group
                  name="BedBlanketWhite"
                  position={[0.286, -0.468, 0.255]}
                  rotation={[1.204, 0.463, 0.05]}
                  scale={[0.585, 0.608, 0.602]}
                >
                  <mesh
                    name="Plane007_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane007_0.geometry}
                    material={materials["shade.017"]}
                  />
                </group>
                <group
                  name="BedFrame"
                  position={[0.015, -0.591, 0.238]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[0.363, 0.887, 0.099]}
                >
                  <mesh
                    name="Cube003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  name="BedMattress"
                  position={[0.015, -0.591, 0.286]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[0.352, 0.861, 0.096]}
                >
                  <mesh
                    name="Cube004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004_0.geometry}
                    material={materials["Root.005"]}
                  />
                </group>
                <group
                  name="BedPillar1"
                  position={[0.894, -0.238, 0.219]}
                  scale={[0.041, 0.048, 0.213]}
                >
                  <mesh
                    name="Cube005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  name="BedPillar2"
                  position={[-0.863, -0.591, 0.29]}
                  scale={[0.041, 0.048, 0.24]}
                >
                  <mesh
                    name="Cube006_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube006_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  name="BedPillar3"
                  position={[-0.85, -0.591, 0.462]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[0.363, 0.887, 0.032]}
                >
                  <mesh
                    name="Cube009_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube009_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  name="BedSheet"
                  position={[0.015, -0.591, 0.513]}
                  rotation={[0.082, -0.067, 1.614]}
                  scale={[0.872, 1.167, 0.492]}
                >
                  <mesh
                    name="Cube007_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube007_0.geometry}
                    material={materials["shelves.010"]}
                  />
                </group>
                <group
                  name="BedTop1"
                  position={[0.894, -0.238, 0.521]}
                  scale={[0.073, 0.073, 0.009]}
                >
                  <mesh
                    name="Cylinder007_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder007_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  name="BedTop2"
                  position={[-0.866, -0.238, 0.585]}
                  scale={[0.073, 0.073, 0.009]}
                >
                  <mesh
                    name="Cylinder008_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder008_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  name="BedTopBar1"
                  position={[0.89, -0.808, 0.383]}
                  rotation={[Math.PI, 0, -Math.PI / 2]}
                  scale={[0.03, 0.03, 0.05]}
                >
                  <mesh
                    name="Cylinder015_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder015_0.geometry}
                    material={materials["cornice.005"]}
                  />
                </group>
                <group
                  name="BedTopBar2"
                  position={[-0.865, -0.808, 0.423]}
                  rotation={[Math.PI, 0, -Math.PI / 2]}
                  scale={[0.03, 0.03, 0.088]}
                >
                  <mesh
                    name="Cylinder016_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder016_0.geometry}
                    material={materials["cornice.005"]}
                  />
                </group>
                <group
                  name="BlankeetOnChairWhite"
                  position={[0.538, 0.67, 0.611]}
                  rotation={[0.102, 0.135, -0.433]}
                  scale={0.221}
                >
                  <mesh
                    name="Plane002_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane002_0.geometry}
                    material={materials["poduha.005"]}
                  />
                </group>
                <group
                  name="CubeOnShelfBlack1"
                  position={[-0.57, 0.871, 1.612]}
                  rotation={[0, 0, 1.614]}
                  scale={[0.066, 0.129, 0.058]}
                >
                  <mesh
                    name="Cube030_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube030_0.geometry}
                    material={materials["FLOOR.005"]}
                  />
                </group>
                <group
                  name="CubeOnShelfBlack2"
                  position={[-0.57, 0.871, 1.733]}
                  rotation={[0, 0, 2.069]}
                  scale={[0.048, 0.07, 0.06]}
                >
                  <mesh
                    name="Cube031_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube031_0.geometry}
                    material={materials["table.005"]}
                  />
                </group>
                <group
                  name="CubeOnShelfGray"
                  position={[0.056, 0.908, 1.118]}
                  rotation={[0, 0, 0.529]}
                  scale={[0.037, 0.054, 0.114]}
                >
                  <mesh
                    name="Cube033_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube033_0.geometry}
                    material={materials["tubes.005"]}
                  />
                </group>
                <group
                  name="CubeOnShelfWhite"
                  position={[-0.365, 0.871, 1.349]}
                  rotation={[0, 0, 1.073]}
                  scale={[0.061, 0.089, 0.07]}
                >
                  <mesh
                    name="Cube032_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube032_0.geometry}
                    material={materials["white.005"]}
                  />
                </group>
                <group
                  name="CurtainBlue"
                  position={[-0.932, -0.551, 1.865]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.072, 0.076, 0.353]}
                >
                  <mesh
                    name="Cylinder006_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder006_0.geometry}
                    material={materials["shade.016"]}
                    morphTargetDictionary={
                      nodes.Cylinder006_0.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.Cylinder006_0.morphTargetInfluences
                    }
                    position={[0.307, 0, -0.071]}
                  />
                </group>
                <group
                  name="Desk"
                  position={[-0.35, 0.272, 0.53]}
                  rotation={[0, 0, -Math.PI]}
                  scale={[0.432, 0.276, 0.033]}
                >
                  <mesh
                    name="Cube001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  ref={buttonToScreenRef}
                  name="FloatingButton"
                  position={[1.742, -1.042, 1.61]}
                  rotation={[-Math.PI / 2, 1.478, -Math.PI]}
                  scale={0.476}
                >
                  <group
                    name="FloatScreen"
                    rotation={[0.014, 0, 0]}
                    scale={0.085}
                  >
                    <group
                      name="FloatScreenMesh"
                      position={[0, 12.359, -0.178]}
                      rotation={[Math.PI / 2, 0, 0]}
                      scale={[1, 1, 0.64]}
                    >
                      <mesh
                        name="CubeFloat"
                        castShadow
                        receiveShadow
                        geometry={nodes.CubeFloat.geometry}
                        material={materials["aluminium.001"]}
                      />
                      <mesh
                        name="CubeFloat_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.CubeFloat_1.geometry}
                        material={materials["matte.002"]}
                      />
                      <mesh
                        name="CubeFloat_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.CubeFloat_2.geometry}
                        material={materials["screen.002"]}
                      >
                        <Html
                          className="w-[335px] h-[215px] rounded-[8px] overflow-y-auto p-0 bg-black hover:opacity-90 overflow-x-hidden"
                          position={[0, 0.05, -0.09]}
                          occlude="blending"
                          rotation-x={-Math.PI / 2}
                          transform
                        >
                          <div
                            className="w-[325px] h-[215px] flex justify-center items-center relative"
                            onPointerDown={(e) => e.stopPropagation()}
                          >
                            <div className="absolute top-0 left-0 h-5 bg-amber-50 w-[110%]" />
                            <button
                              className={`text-white shadow rounded text-5xl cursor-pointer h-full w-full font-bold ${poppins.className}`}
                              onClick={() => setCamera(true)}
                            >
                              <p className="pb-3">
                                {t("workroom3D-viewlaptop")}
                              </p>
                              <p>&gt;_</p>
                            </button>
                          </div>
                        </Html>
                      </mesh>
                    </group>
                  </group>
                </group>
                <group
                  name="HangerAttachment"
                  position={[-0.947, -0.885, 1.883]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  scale={0.05}
                >
                  <mesh
                    name="Cylinder014_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder014_0.geometry}
                    material={materials["cornice.005"]}
                  />
                </group>
                <group
                  name="HangerBar"
                  position={[-0.871, -0.001, 1.884]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.072, 0.072, 0.859]}
                >
                  <mesh
                    name="Cylinder004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder004_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  name="HangerCircle"
                  position={[-0.871, 0.125, 1.875]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.087, 0.087, 0.972]}
                >
                  <mesh
                    name="Cylinder011_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder011_0.geometry}
                    material={materials["cornice.005"]}
                  />
                </group>
                <group
                  name="HangerCircle2"
                  position={[-0.871, 0.7, 1.875]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.087, 0.087, 0.972]}
                >
                  <mesh
                    name="Cylinder012_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder012_0.geometry}
                    material={materials["cornice.005"]}
                  />
                </group>
                <group
                  name="HangerSmallBar"
                  position={[-0.912, -0.001, 1.851]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.017, 0.017, 0.901]}
                >
                  <mesh
                    name="Cylinder005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder005_0.geometry}
                    material={materials["cornice.005"]}
                  />
                </group>
                <group
                  name="ItemOnDesk1"
                  position={[-0.467, 0.13, 0.635]}
                  rotation={[1.571, 1.352, 0]}
                  scale={[0.048, 0.102, 0.042]}
                >
                  <mesh
                    name="Cube026_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube026_0.geometry}
                    material={materials["Material.017"]}
                  />
                  <mesh
                    name="Cube026_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube026_1.geometry}
                    material={materials["lamp_wood.005"]}
                  />
                </group>
                <group
                  name="ItemOnDesk2"
                  position={[0.029, 0.059, 0.636]}
                  rotation={[-1.571, 1.227, 3.142]}
                  scale={[0.048, 0.102, 0.042]}
                >
                  <mesh
                    name="Cube027_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube027_0.geometry}
                    material={materials["Material.017"]}
                  />
                  <mesh
                    name="Cube027_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube027_1.geometry}
                    material={materials["lamp_wood.005"]}
                  />
                </group>
                <group
                  name="ItemOnDesk3"
                  position={[-0.319, 0.08, 0.564]}
                  rotation={[Math.PI, 0, -1.913]}
                  scale={[0.035, 0.074, 0.03]}
                >
                  <mesh
                    name="Cube028_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube028_0.geometry}
                    material={materials["Material.017"]}
                  />
                </group>
                <group
                  name="ItemOnDeskFlat"
                  position={[-0.498, 0.309, 0.533]}
                  rotation={[0, 0, 0.377]}
                  scale={[0.067, 0.055, 0.055]}
                >
                  <mesh
                    name="Plane008_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane008_0.geometry}
                    material={materials["FLOOR.005"]}
                  />
                </group>
                <group
                  name="ItemUnderBed1"
                  position={[0.869, -0.705, 0.064]}
                  rotation={[0, 0, -0.306]}
                  scale={[0.066, 0.141, 0.058]}
                >
                  <mesh
                    name="Cube024_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube024_0.geometry}
                    material={materials["Material.017"]}
                  />
                </group>
                <group
                  name="ItemUnderBed2"
                  position={[0.837, -0.418, 0.066]}
                  rotation={[0, 0, 1.164]}
                  scale={[0.066, 0.141, 0.058]}
                >
                  <mesh
                    name="Cube025_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube025_0.geometry}
                    material={materials["lamp_wood.005"]}
                  />
                </group>
                <group
                  name="LambOuterRed"
                  position={[-0.69, 0.185, 0.84]}
                  rotation={[0, 0, 0.366]}
                  scale={[0.37, 0.37, 0.166]}
                >
                  <mesh
                    name="Cylinder_0002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder_0002.geometry}
                    material={materials["lamp.020"]}
                  />
                </group>
                <group
                  name="LampFrame"
                  position={[-0.69, 0.185, 0.84]}
                  rotation={[0, 0, 0.366]}
                  scale={[0.367, 0.367, 0.165]}
                >
                  <mesh
                    name="Cylinder003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder003_0.geometry}
                    material={materials["lamp_wood.005"]}
                  />
                </group>
                <group
                  name="LampInner"
                  position={[-0.69, 0.185, 0.817]}
                  rotation={[0, 0, 0.366]}
                  scale={[0.227, 0.227, 0.102]}
                >
                  <mesh
                    name="Cylinder002_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder002_0.geometry}
                    material={materials["lamp_light.005"]}
                  />
                </group>
                <group
                  name="LampStand"
                  position={[-0.69, 0.185, 0.598]}
                  rotation={[0, 0, 0.366]}
                  scale={[0.305, 0.305, 0.102]}
                >
                  <mesh
                    name="Cylinder001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder001_0.geometry}
                    material={materials["lamp_wood.005"]}
                  />
                </group>
                <group
                  name="LaptopSample"
                  position={[-0.254, 0.365, 0.532]}
                  rotation={[-Math.PI / 2, -0.142, Math.PI]}
                  scale={0.476}
                >
                  <group
                    name="base"
                    position={[-0.015, 0, 0.029]}
                    scale={0.085}
                  >
                    <mesh
                      name="Cube002"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube002.geometry}
                      material={materials.aluminium}
                    />
                    <mesh
                      name="Cube002_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube002_1.geometry}
                      material={materials.trackpad}
                    />
                  </group>
                  <mesh
                    name="keyboard"
                    castShadow
                    receiveShadow
                    geometry={nodes.keyboard.geometry}
                    material={materials.keys}
                    position={[0.137, 0.009, 0.034]}
                    scale={0.085}
                  />
                  <group
                    name="screenflip"
                    rotation-x={-0.425}
                    position={[-0.015, 0.005, -0.223]}
                    scale={0.085}
                  >
                    <group
                      ref={screenRef}
                      name="screen"
                      position={[0, 2.965, -0.13]}
                      rotation={[Math.PI / 2, 0, 0]}
                    >
                      <mesh
                        name="Cube008"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008.geometry}
                        material={materials.aluminium}
                      />
                      <mesh
                        name="Cube008_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_1.geometry}
                        material={materials["matte.001"]}
                      />
                      <mesh
                        name="Cube008_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_2.geometry}
                        material={materials["screen.001"]}
                      >
                        <Html
                            className="w-[334px] h-[216px] bg-[#f0f0f0] rounded-[3px] overflow-hidden p-0 scrollbar-thin scrollbar-thumb-gray-400 scrollbar-track-white"
                            rotation-x={-Math.PI / 2}
                            position={[0, 0.05, -0.09]}
                            transform
                            occlude="blending"
                          >
                            <DarkModeContextBridge>
                              <div
                                className="w-[668px] h-[432px] scale-[0.5] origin-top-left relative"
                                onPointerDown={(e) => e.stopPropagation()}
                              >
                                <div
                                  className="h-full overflow-y-auto relative"
                                  ref={overlayScrollRef}
                                >
                                  <div className="sticky top-0 z-50 h-[70px]">
                                    <Navbar is3D={true} />
                                  </div>
                                  <Works is3D={true} />
                                </div>
                              </div>
                            </DarkModeContextBridge>
                        </Html>
                      </mesh>
                    </group>
                  </group>
                  <mesh
                    name="touchbar"
                    castShadow
                    receiveShadow
                    geometry={nodes.touchbar.geometry}
                    material={materials.touchbar}
                    position={[-0.015, 0.006, -0.157]}
                    scale={0.085}
                  />
                </group>
                <group
                  name="Pillow"
                  position={[-0.62, -0.563, 0.394]}
                  rotation={[-0.122, -0.032, -0.131]}
                  scale={[0.207, 0.302, 0.068]}
                >
                  <mesh
                    name="Cube012_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube012_0.geometry}
                    material={materials["poduha.005"]}
                  />
                </group>
                <group
                  name="PlantGreen1"
                  position={[0.118, 0.912, 1.771]}
                  rotation={[1.141, 0.439, 1.843]}
                  scale={[0.078, 0.028, 0.013]}
                >
                  <mesh
                    name="Plane003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane003_0.geometry}
                    material={materials["WEED.005"]}
                  />
                </group>
                <group
                  name="PlantGreen2"
                  position={[0.191, 0.91, 1.739]}
                  rotation={[1.145, 0.416, 1.832]}
                  scale={[0.057, 0.021, 0.01]}
                >
                  <mesh
                    name="Plane004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane004_0.geometry}
                    material={materials["WEED.005"]}
                  />
                </group>
                <group
                  name="PlantGreen3"
                  position={[0.082, 0.852, 1.771]}
                  rotation={[0.196, 1.176, 3.01]}
                  scale={[0.057, 0.021, 0.01]}
                >
                  <mesh
                    name="Plane005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane005_0.geometry}
                    material={materials["WEED.005"]}
                  />
                </group>
                <group
                  name="PlantGreen4"
                  position={[0.147, 0.828, 1.722]}
                  rotation={[-1.164, -0.305, -1.362]}
                  scale={[0.057, 0.021, 0.01]}
                >
                  <mesh
                    name="Plane006_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane006_0.geometry}
                    material={materials["WEED.005"]}
                  />
                </group>
                <group
                  name="PlantPot"
                  position={[0.155, 0.875, 1.588]}
                  scale={[-0.329, -0.21, -0.006]}
                >
                  <mesh
                    name="Cube022_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube022_0.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group name="Point001" position={[-0.693, 0.187, 0.888]}>
                  <group name="Point002" />
                </group>
                <group
                  name="PotBrownOnShelf"
                  position={[0.374, 0.903, 1.03]}
                  scale={[-0.238, -0.152, -0.004]}
                >
                  <mesh
                    name="Cube034_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube034_0.geometry}
                    material={materials["lamp_wood.005"]}
                  />
                </group>
                <group
                  name="RedChair"
                  position={[0.639, 0.713, 0.218]}
                  scale={[-0.26, -0.21, -0.15]}
                >
                  <mesh
                    name="Cube021_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube021_0.geometry}
                    material={materials["shade.015"]}
                  />
                  <mesh
                    name="Cube021_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube021_1.geometry}
                    material={materials["material.005"]}
                  />
                </group>
                <group
                  name="RoomWall"
                  position={[0.006, 0, 0]}
                  rotation={[0, 0, -Math.PI]}
                >
                  <mesh
                    name="Cube_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_0.geometry}
                    material={materials["WALLS.005"]}
                  />
                  <mesh
                    name="Cube_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_1.geometry}
                    material={materials["FLOOR.005"]}
                  />
                  <mesh
                    name="Cube_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_2.geometry}
                    material={materials["material_21.005"]}
                  />
                </group>
                <group
                  name="ShelfFrame"
                  position={[-0.478, 0.903, 1.539]}
                  scale={[0.273, 0.088, 0.009]}
                >
                  <mesh
                    name="Cube013_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube013_0.geometry}
                    material={materials["shelves.011"]}
                  />
                </group>
                <group
                  name="ShelfFrame2"
                  position={[0.177, 0.903, 1.539]}
                  scale={[0.273, 0.088, 0.009]}
                >
                  <mesh
                    name="Cube014_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube014_0.geometry}
                    material={materials["shelves.011"]}
                  />
                </group>
                <group
                  name="ShelfHorizontal"
                  position={[-0.216, 0.903, 1.539]}
                  scale={[0.273, 0.077, 0.009]}
                >
                  <mesh
                    name="Cube019_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube019_0.geometry}
                    material={materials["shelves.011"]}
                  />
                </group>
                <group
                  name="ShelfHorizontalBar2"
                  position={[0.45, 0.903, 1.539]}
                  scale={[0.273, 0.077, 0.009]}
                >
                  <mesh
                    name="Cube017_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube017_0.geometry}
                    material={materials["shelves.011"]}
                  />
                </group>
                <group
                  name="ShelfPillar"
                  position={[-0.215, 0.824, 1.266]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.273, 0.283, 0.009]}
                >
                  <mesh
                    name="Cube020_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube020_0.geometry}
                    material={materials["shelves.011"]}
                  />
                </group>
                <group
                  name="ShelfPillar2"
                  position={[0.45, 0.824, 1.266]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.273, 0.283, 0.009]}
                >
                  <mesh
                    name="Cube018_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube018_0.geometry}
                    material={materials["shelves.011"]}
                  />
                </group>

                <group
                  ref={wallPictureBrownRef}
                  name="WallPictureBrown"
                  position={[1.006, 0.986, 1.178]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={[0.013, 0.399, 0.407]}
                >
                  <mesh
                    name="Cube037_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube037_0.geometry}
                    material={materials["table.005"]}
                  />
                  <mesh
                    name="Cube037_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube037_1.geometry}
                    material={materials["lamp.012"]}
                  >
                    <WallCertificates
                      visible={showWallHtml}
                      onHoverPractitioner={setHoveredImageCertificate1}
                      onHoverArchitect={setHoveredImageCertificate2}
                    />
                  </mesh>
                </group>

                <group
                  position={[1.006, 0.986, 1.178]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={[0.011, 0.086, 0.125]}
                >
                  {showWallHtml && hoveredImageCertificate1 && (
                    <Html
                      rotation-x={Math.PI / 2}
                      rotation-y={Math.PI / 2}
                      position={[2, 4, 0]}
                      transform
                      occlude="blending"
                      className="pointer-events-none"
                    >
                      <div className="w-[200px] rounded shadow-lg overflow-hidden bg-white text-sm transition-opacity duration-300">
                        <Image
                          src="/certificates/aws-cloud-practitioner.jpg"
                          alt="Zoomed My Certificate 1"
                          width={200}
                          height={150}
                          className="w-full h-auto"
                        />
                        <div className="p-2 text-gray-800">
                          <p className="font-semibold">
                            Cloud Practitioner Certificate
                          </p>
                          <p>{t("myCertificateDescription")}</p>
                        </div>
                      </div>
                    </Html>
                  )}
                  {showWallHtml && hoveredImageCertificate2 && (
                    <Html
                      rotation-x={Math.PI / 2}
                      rotation-y={Math.PI / 2}
                      position={[2, 4, 0]}
                      transform
                      occlude="blending"
                      className="pointer-events-none"
                    >
                      <div className="w-[200px] rounded shadow-lg overflow-hidden bg-white text-sm transition-opacity duration-300">
                        <Image
                          src="/certificates/aws-solutions-architect.jpg"
                          alt="Zoomed My Certificate 2"
                          width={200}
                          height={150}
                          className="w-full h-auto"
                        />
                        <div className="p-2 text-gray-800">
                          <p className="font-semibold">
                            Solution Architect Certificate
                          </p>
                          <p>{t("myCertificateDescription")}</p>
                        </div>
                      </div>
                    </Html>
                  )}
                </group>

                <group
                  ref={wallPictureBlackRef}
                  name="WallPictureBlack"
                  position={[-0.97, 0.866, 1.423]}
                  scale={[0.011, 0.086, 0.125]}
                >
                  <mesh
                    name="Cube035_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube035_0.geometry}
                    material={materials["lamp_wood.005"]}
                  />
                  <mesh
                    name="Cube035_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube035_1.geometry}
                    material={materials["white.005"]}
                  >
                    {showWallHtml && (
                    <Html
                      className="w-[62px] h-[70px] bg-[#f0f0f0] p-0"
                      rotation-x={Math.PI / 2}
                      rotation-y={Math.PI / 2}
                      position={[0, 0, 0]}
                      transform
                      occlude="blending"
                    >
                      <Image
                        src="https://drive.google.com/thumbnail?id=1w7hT1xl_rgbyf1mDJ7OGQAavx788wwQ5&sz=w1000"
                        alt="My Couple"
                        width={62}
                        height={70}
                        className="w-full h-full object-cover cursor-pointer"
                        onMouseEnter={() => setHoveredImageCouple(true)}
                        onMouseLeave={() => setHoveredImageCouple(false)}
                      />
                    </Html>
                    )}
                  </mesh>
                  {showWallHtml && hoveredImageCouple && (
                    <Html
                      rotation-x={Math.PI / 2}
                      rotation-y={Math.PI / 2}
                      position={[2, -6, -1]}
                      transform
                      occlude="blending"
                      className="pointer-events-none"
                    >
                      <div className="w-[200px] rounded shadow-lg overflow-hidden bg-white text-sm transition-opacity duration-300">
                        <Image
                          src="https://drive.google.com/thumbnail?id=1w7hT1xl_rgbyf1mDJ7OGQAavx788wwQ5&sz=w1000"
                          alt="Zoomed My Couple"
                          width={200}
                          height={150}
                          className="w-full h-auto"
                        />
                        <div className="p-2 text-gray-800">
                          <p className="font-semibold">{t("myLove")}</p>
                          <p>{t("myLoveDescription")}</p>
                        </div>
                      </div>
                    </Html>
                  )}
                </group>

                <group
                  ref={wallPictureRedRef}
                  name="WallPictureRed"
                  position={[-0.97, 0.866, 1.068]}
                  scale={[0.011, 0.086, 0.125]}
                >
                  <mesh
                    name="Cube036_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube036_0.geometry}
                    material={materials["cornice.005"]}
                  />
                  <mesh
                    name="Cube036_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube036_1.geometry}
                    material={materials["WEED.005"]}
                  >
                    {showWallHtml && (
                    <Html
                      className="w-[62px] h-[70px] bg-[#f0f0f0] p-0"
                      rotation-x={-Math.PI / 2}
                      rotation-y={Math.PI / 2}
                      position={[0, 0, 0]}
                      transform
                      occlude="blending"
                    >
                      <Image
                        src="https://drive.google.com/thumbnail?id=1a25DxaL9PNJk6FFiqT2K0SqQMIjBojif&sz=w1000"
                        alt="My Cat"
                        width={62}
                        height={70}
                        className="w-full h-full object-cover cursor-pointer"
                        onMouseEnter={() => setHoveredImageCat(true)}
                        onMouseLeave={() => setHoveredImageCat(false)}
                      />
                    </Html>
                    )}
                  </mesh>
                  {showWallHtml && hoveredImageCat && (
                    <Html
                      rotation-x={Math.PI / 2}
                      rotation-y={Math.PI / 2}
                      position={[2, -6, 2]}
                      transform
                      occlude="blending"
                      className="pointer-events-none"
                    >
                      <div className="w-[200px] rounded shadow-lg overflow-hidden bg-white text-sm transition-opacity duration-300">
                        <Image
                          src="https://drive.google.com/thumbnail?id=1a25DxaL9PNJk6FFiqT2K0SqQMIjBojif&sz=w1000"
                          alt="Zoomed My Cat"
                          width={200}
                          height={150}
                          className="w-full h-auto"
                        />
                        <div className="p-2 text-gray-800">
                          <p className="font-semibold">{t("myCat")}</p>
                          <p>{t("myCatDescription")}</p>
                        </div>
                      </div>
                    </Html>
                  )}
                </group>

                <group
                  name="WindowBelow"
                  position={[-0.978, 0.273, 0.296]}
                  scale={[-0.012, -0.558, -0.2]}
                >
                  <mesh
                    name="Cube016_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube016_0.geometry}
                    material={materials["tubes.005"]}
                  />
                </group>
                <group
                  name="WindowBottom"
                  position={[-1.095, 0, 0.609]}
                  scale={[0.14, 0.712, 0.027]}
                >
                  <mesh
                    name="Cube010_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube010_0.geometry}
                    material={materials["white.005"]}
                  />
                </group>
                <group
                  name="WindowInner"
                  position={[-0.488, 0, 0.05]}
                  rotation={[0, 0, -Math.PI]}
                  scale={[0.556, 1.089, 0.999]}
                >
                  <mesh
                    name="Cube011_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube011_0.geometry}
                    material={materials["white.005"]}
                  />
                </group>
                <group
                  name="WindowPillar"
                  position={[-1.084, 0.006, 1.155]}
                  scale={[-0.056, -0.038, -0.55]}
                >
                  <mesh
                    name="Cube008_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube008_0.geometry}
                    material={materials["white.005"]}
                  />
                </group>
                <group
                  name="WoodChair"
                  position={[-0.365, 0.741, 0.262]}
                  rotation={[0, 0, 0.404]}
                  scale={[0.158, 0.158, 0.025]}
                >
                  <mesh
                    name="Cube015_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube015_0.geometry}
                    material={materials["lamp_wood.005"]}
                  />
                  <mesh
                    name="Cube015_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube015_1.geometry}
                    material={materials["poduha.005"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    );
  }
);

useGLTF.preload("/models/isometric_room_fin_3.glb", true);

MyRoom.displayName = "MyRoom";
export default MyRoom;
